[package]
name = "example_legacy_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
migration_repr = {path = "../migration_repr"}
migration_macro = {path = "../migration_macro"}
