[package]
name = "migration_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.35"
syn = "2.0.49"
migration_repr = {path = "../migration_repr"}


[lib]
proc-macro = true
